version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app-${APP_ENV:-production}
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-'self'}
    ports:
      - "${PORT:-3000}:80"
    # volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf.template
      # - ./entrypoint.sh:/docker-entrypoint.sh
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge